### PR TITLE
Adding Gitlab to all clouds as VCS option

### PR DESCRIPTION
**Pull request by dustinvanbuskirk**

### CODE REVIEW

**Review by lrochette — APPROVED** [review]
it seems you add very similar code to each provider. Would it make sense in the future to modularize it?
I'll give it a try on EKS (as I was having trouble getting an account on Azure without promising my first born)

**Comment by dustinvanbuskirk** [comment]
> it seems you add very similar code to each provider. Would it make sense in the future to modularize it? I'll give it a try on EKS (as I was having trouble getting an account on Azure without promising my first born)

You're correct but and I tried this but eventually since I am lacking formal Terraform knowledge put it on the back burner for a future iterations.

Since this is finally to me a MVP on the installation and configuration.  I can take time now to try the module approach again with the voting application portion.

My goal of this work is that it will be the defacto starting point for anyone wanting a sandbox.  With that I think we can log improvements as issues here on the repository and start watching for votes on what to do next.

I'll create an issues after merge to create modules for github, gitlab and isc configuration.

**Comment by dustinvanbuskirk** [comment]
I need to update to latest Helm charts and constrain those after last night's release.

**Review by lrochette — APPROVED** [review]

**Comment by twerthi** [comment]
Suggestion - make the resource group a variable.  Some organizations may have a naming convention they're supposed to follow and having the flexibility for the resource group to follow that might be needed.

**Pull request merged**
